  
title = "Beg Bounty"
baseURL = "https://begbounty.com"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = false
math = false          # enable KaTeX (https://katex.org/) globally

[params]
  author = "Parsia"
  description = "Because You Gotta Beg for Disclosure!"
  [params.footer]
    text = "Built with Hugo and the 'Researcher' theme by Olivier Roques"
    url = "https://github.com/parsiya/begbounty.com"

[menu]
  [[menu.main]]
    name = "My Personal Website"
    url = "https://parsiya.net"
    weight = 3
